### PR TITLE
added getActiveEnergyBurned method

### PR DESCRIPTION
**Pull request by ca**
I needed to use this the other day so I implemented it, may be helpful for others.

### CODE REVIEW

**Comment by MaximeHeckel** [comment]
I'd also need this

**Comment by nehvaleem** [comment]
I would really appreciate if this PR could be merged :)
cc @GregWilson

**Comment by ca** [comment]
@terrillo can we get this in on the new repo?

**Comment by terrillo** [comment]
@ca @nehvaleem @MaximeHeckel I'll look into merging this in today 👍

**Comment by ca** [comment]
@terrillo Great, thanks for the work in keeping this library up!

**Comment by terrillo** [comment]
@nehvaleem @MaximeHeckel available in version 0.6.1v. Already pushed to NPM. Let me if you run into any problems. @ca I also gave you credit :D https://github.com/terrillo/rn-apple-healthkit/pull/5

**Comment by ca** [comment]
I appreciate that very much! Glad it's available now :)

**Pull request closed without merging**
