### PR TITLE
Save mindfulness session

### PR DESCRIPTION
**Pull request by skleest**
Saves mindfulness session

### CODE REVIEW

**Comment by terrillo** [comment]
@skleest can you update the readme as well?

**Comment by paulief** [comment]
@terrillo I was just wondering if you think this'll be merged soon.

Also, just a related question for @skleest : Do I need to target iOS 10 only to use this? Or is there a way to conditionally include the Mindfulness part of the library on older SDKs?

Thanks guys for all your work on this!

**Comment by paulief** [comment]
@skleest sorry, you can ignore my question. It was just an Xcode issue I was running into.

**Comment by simonstead** [comment]
Yeah I'd love to know the progress on this too 😀

**Comment by EnricoGallus** [comment]
+1

**Comment by seanadkinson** [comment]
@skleest I've published a branch that can read Mindful Minutes (maybe I should rename to Mindful Session?).  The repo is here: https://github.com/ProvataHealth/react-native-apple-healthkit

It's available on npm with `yarn add react-native-apple-healthkit-rn0.40@0.3.2`

If you are interested in creating a PR with the ability to write mindful minutes, I'll merge and publish from that repo.  Otherwise I'll probably get to it once we need that ability in our app.

**Comment by skleest** [comment]
Hi @paulief, I've been using it for only iOS 10+ using JS (check for device info), and it hasn't been a problem for iOS <10. @seanadkinson this PR includes reading as well!

Currently I'm using RN 0.39 so I'm refraining from updating this repo; if anyone else can fix the small merge conflict, should be good to go.

**Pull request merged**
